Travis CI fix
File "/home/travis/build/mjirik/io3d/io3d/datareader.py", line 9, in <module>
   import sed3
ModuleNotFoundError: No module named 'sed3'

Caused by moving 'import sed3' on the top of the file